version: '2'
services:
  frontend:
    command:  /bin/sh -c "npm run setup && npm run startDocker"
    image: node
    working_dir: /opt
    ports:
      - "4200:4200"
    volumes:
      - .:/opt
      - ~/.ssh:/root/.ssh
    environment:
      BACKEND_SERVER: http://backend:3000
networks:
  default:
    external:
      name: apirepositiveio_default
