version: '2'
services:
  frontend:
    command:  /bin/sh -c "npm run setup && npm run startDocker"
    image: node:6.4
    working_dir: /opt
    ports:
      - "4200:4200"
      - "49152:49152"
    volumes:
      - .:/opt
      - ~/.ssh:/root/.ssh
    environment:
      #BACKEND_SERVER: http://localhost:3000
      BACKEND_SERVER: https://api-staging.repositive.io
