version: '2'
services:
  frontend:
    command:  /bin/sh -c "npm run setup && npm run startDocker"
    image: node
    working_dir: /opt
    ports:
      - "4200:4200"
      - "49152:49152"
    volumes:
      - .:/opt
      - ~/.ssh:/root/.ssh
      - /opt/bower_components
      - /opt/node_modules
    environment:
      BACKEND_SERVER: http://api:3000
    networks:
      - api
networks:
  api:
    external:
      name: api_service
