apiVersion: v1
kind: Service
metadata:
  name: discover
  namespace: pdx
  labels:
    app: discover
spec:
  selector:
    app: discover
  ports:
    - port: 80
      name: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discover
  namespace: pdx
  labels:
    app: discover
    env: pdx
    criticality: high
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discover
        env: pdx
        criticality: high
    spec:
      containers:
        - name: discover
          image: registry.repositive.io:5000/discover:beta1
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regsecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discover
  labels:
    app: discover
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: discover-pdx.repositive.io
    http:
      paths:
      - backend:
          serviceName: discover
          servicePort: 80
