---
# To install packages that need to be built from source
- name: Make sure build-essential is installed
  apt:
    name: build-essential
    state: present

- name: Add NodeSources apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSources repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"

- name: Ensure nodeJS and npm are installed
  apt:
    name: "nodejs={{ nodejs_version }}-*"
    state: present
    update_cache: yes

