version: 2

workflows:
  version: 2
  test_and_release:
    jobs:

      - compute_tag:
          filters:
            branches:
              only:
                - master
                - production

      - test_and_make:
          filters:
            branches:
              ignore:
                - production

      - build_container_dev:
          filters:
            branches:
              only:
                - master
          requires:
            - test_and_make
            - compute_tag

      - build_container_local:
          filters:
            branches:
              only:
                - master
          requires:
            - test_and_make
            - compute_tag

      - build_container_prod:
          filters:
            branches:
              only:
                - master
          requires:
            - test_and_make
            - compute_tag

      - release_dev:
          filters:
            branches:
              only:
                - master
          requires:
            - build_container_dev
            - compute_tag

      - release_prod:
          filters:
            branches:
              only:
                - production
          requires:
            - compute_tag

      - create_release_tag:
          requires:
            - release_dev
            - release_prod

deploy_image: &deploy_image
  docker:
    - image: reposibot/deployer:latest
  steps:
    - attach_workspace:
        at: .
    - run:
        name: release staging
        command: |
          TAG="$(cat tag.txt)-${TARGET}"
          curl -sSO -u "${DEPLOYER_USERNAME}":"${DEPLOYER_PASSWORD}" \
            "https://deployer.repositive.io/scripts/deploy.sh"
          sh deploy.sh "$CIRCLE_PROJECT_REPONAME:$TAG" $CLUSTER $CONFIG_PATH $CIRCLE_BRANCH

build_container: &build_container
  docker:
    - image: circleci/node:10-browsers
  steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run:
        name: Build ember app
        command: |
          REPO="${CIRCLE_PROJECT_REPONAME}"
          TAG="$(cat tag.txt)"
          API_BASE_URL="${API_BASE_URL}"

          # build ember
          node_modules/ember-cli/bin/ember build --environment "${EMBER_ENV}"
          
          # Build the Container
          docker build -t app .

          # Authenticate to docker
          echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin gcr.io/repositive-gcr

          # TAG and Push to gcr.io/repositive-gcr (GCP)
          docker tag app "gcr.io/repositive-gcr/${REPO}:latest-${TARGET}"
          docker tag app "gcr.io/repositive-gcr/${REPO}:${TAG}-${TARGET}"
          docker push "gcr.io/repositive-gcr/${REPO}:latest-${TARGET}"
          docker push "gcr.io/repositive-gcr/${REPO}:${TAG}-${TARGET}"

jobs:

  compute_tag:
    machine: true
    steps:
      - checkout
      - run: echo "$(git rev-parse --short HEAD)" > tag.txt
      - persist_to_workspace:
          root: .
          paths:
            - tag.txt

  test_and_make:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build_container_local:
    environment:
      - TARGET: 'local'
      - EMBER_ENV: 'development'
      - API_BASE_URL: 'http://localhost:3000'
    <<: *build_container

  build_container_dev:
    environment:
      - TARGET: 'development'
      - EMBER_ENV: 'staging'
      - API_BASE_URL: 'https://dev.repositive.io/discover/api'
    <<: *build_container

  build_container_prod:
    environment:
      - TARGET: 'production'
      - EMBER_ENV: 'production'
      - API_BASE_URL: 'https://repositive.io/discover/api'
    <<: *build_container

  create_release_tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Create release tag
          command: |
            TAG=$(date +"%Y%m%d%H%M%S")
            SHA="$(git rev-parse HEAD)"
            curl -fsS -u "${GITHUB_USERNAME}":"${GITHUB_PASSWORD}" \
              -d '{"ref":"refs/tags/'"${TAG}"'", "sha":"'"${SHA}"'"}' \
              -X POST "https://api.github.com/repos/repositive/${CIRCLE_PROJECT_REPONAME}/git/refs"

  release_dev:
    environment:
      - TARGET: 'development' # This is needed to build the right image tag! ${TAG}-${TARGET}
      - CLUSTER: 'cmp-dev' # We only use one cluster for discover & cmp segregated by namespace. The namespace is defined in the k8s files.
      - CONFIG_PATH: '.circleci/k8s.development.yml'
    <<: *deploy_image

  release_prod:
    environment:
      - TARGET: 'production' # This is needed to build the right image tag! ${TAG}-${TARGET}
      - CLUSTER: 'cmp-prod' # We only use one cluster for discover & cmp segregated by namespace. The namespace is defined in the k8s files.
      - CONFIG_PATH: '.circleci/k8s.production.yml'
    <<: *deploy_image
