version: 2

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_and_make
      - build_container_local:
          filters:
            branches:
              only:
                - master
          requires:
            - test_and_make
      - build_container_qa:
          filters:
            branches:
              only:
                - master
          requires:
            - test_and_make
      - build_container_dev:
          filters:
            branches:
              only:
                - master
          requires:
            - test_and_make
      - release_dev:
          requires:
            - build_container_dev
      - build_container_demo:
          filters:
            branches:
              only:
                - production
          requires:
            - test_and_make
      - release_demo:
          requires:
            - build_container_demo
      - build_container_production:
          filters:
            branches:
              only:
                - production
          requires:
            - test_and_make
      - release_production:
          requires:
            - build_container_production
      - create_release_tag:
          requires:
            - release_production

deploy_image: &deploy_image
  docker:
    - image: reposibot/deployer:latest
  steps:
    - attach_workspace:
        at: .
    - run:
        name: release staging
        command: |
          TAG="$(cat tag.txt)-${TARGET}"
          curl -sSO -u "${DEPLOYER_USERNAME}":"${DEPLOYER_PASSWORD}" \
            "https://deployer.repositive.io/scripts/deploy.sh"
          sh deploy.sh "$CIRCLE_PROJECT_REPONAME:$TAG" $CLUSTER $CONFIG_PATH

build_container: &build_container
  docker:
    - image: circleci/node:8.5-browsers
  steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run:
        name: Build ember app
        command: |
          REPO="${CIRCLE_PROJECT_REPONAME}"
          TAG="$(cat tag.txt)"
          API_BASE_URL="${API_BASE_URL}"

          node_modules/ember-cli/bin/ember build --environment "${EMBER_ENV}"
          docker build -t app .
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.repositive.io:5000
          docker tag app "registry.repositive.io:5000/${REPO}:latest-${TARGET}"
          docker tag app "registry.repositive.io:5000/${REPO}:${TAG}-${TARGET}"
          docker push "registry.repositive.io:5000/${REPO}:latest-${TARGET}"
          docker push "registry.repositive.io:5000/${REPO}:${TAG}-${TARGET}"

jobs:
  test_and_make:
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: echo "$(git rev-parse --short HEAD)" > tag.txt
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - tag.txt

  build_container_local:
    environment:
      - TARGET: 'local'
      - EMBER_ENV: 'local-development'
      - API_BASE_URL: 'http://localhost:3000'
    <<: *build_container

  build_container_qa:
    environment:
      - TARGET: 'qa'
      - EMBER_ENV: 'staging'
      - API_BASE_URL: 'http://proxy:3000'
    <<: *build_container

  build_container_dev:
    environment:
      - TARGET: 'dev'
      - EMBER_ENV: 'staging'
      - API_BASE_URL: 'https://api-dev.repositive.io'
    <<: *build_container

  build_container_production:
    environment:
      - TARGET: 'prod'
      - EMBER_ENV: 'production'
      - API_BASE_URL: 'https://api.repositive.io'
    <<: *build_container

  create_release_tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Create release tag
          command: |
            TAG="$(date +%s)"
            SHA="$(git rev-parse HEAD)"
            curl -fsS -u "${GITHUB_USERNAME}":"${GITHUB_PASSWORD}" \
              -d '{"ref":"refs/tags/'"${TAG}"'", "sha":"'"${SHA}"'"}' \
              -X POST "https://api.github.com/repos/repositive/${CIRCLE_PROJECT_REPONAME}/git/refs"

  release_dev:
    environment:
      - CLUSTER: 'dis-dev'
    <<: *deploy_image

  release_production:
    environment:
      - CLUSTER: 'discover'
    <<: *deploy_image
