apiVersion: v1
kind: Service
metadata:
  namespace: discover
  labels:
    app: discover
  name: discover
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: discover
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discover
  namespace: discover
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: discover
    spec:
      containers:
      - image: registry.repositive.io:5000/discover-frontend:${TAG}-dis-prod
        imagePullPolicy: IfNotPresent
        name: discover
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets:
      - name: regsecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discover
  namespace: discover
  labels:
    app: discover
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: discover.repositive.io
    http:
      paths:
      - backend:
          serviceName: discover
          servicePort: 80
  tls:
  - secretName: discover-tls-cert
    hosts:
    - discover.repositive.io
