apiVersion: v1
kind: Service
metadata:
  name: discover
  namespace: discover
  labels:
    app: discover
spec:
  selector:
    app: discover
  ports:
    - port: 80
      name: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discover
  namespace: discover
  labels:
    app: discover
    env: staging
    criticality: high
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: discover
        env: staging
        criticality: high
    spec:
      containers:
        - image: gcr.io/repositive-gcr/discover-frontend:${TAG}
          name: discover
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regsecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discover
  namespace: discover
  labels:
    app: discover
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: dev.repositive.io
    http:
      paths:
      - path: /discover
        backend:
          serviceName: discover
          servicePort: 80
  tls:
    - secretName: cmp-platform-tls-cert
      hosts:
        - dev.repositive.io
