apiVersion: v1
kind: Service
metadata:
  name: discover
  labels:
    app: discover
spec:
  selector:
    app: discover
  ports:
    - port: 80
      name: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discover
  labels:
    app: discover
    env: staging
    criticality: high
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: discover
        env: staging
        criticality: high
    spec:
      containers:
        - name: discover
          image: registry.repositive.io:5000/discover:${TAG}
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regsecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discover
  labels:
    app: discover
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: discover-dev.repositive.io
    http:
      paths:
      - backend:
          serviceName: discover
          servicePort: 80
  tls:
    - secretName: discover-tls-cert
      hosts:
        - discover-dev.repositive.io