# Staging settings
---
apiBaseURL: http://backend-staging-amzn-us-east-1.repositive.io
build:
  environment: staging

deploy:
  s3:
    bucket:
    region:
  ssh-tunnel:
    host: frontend-staging-amzn-us-east-1.repositive.io
    username: repositive
  redis:
    host: localhost
    allowOverwrite: true

fingerprint:
  enabled: true
  # URL to prepend to assets
  prepend: http://s3.amazonaws.com/frontend-staging-amzn-us-east-1.repositive.io/
sourcemaps:
  enabled: true
minifyCSS: true
minifyJS: true
pipeline:
  activateOnDeploy: true
# Ember environment
environment:
  torii:
    providers:
      google-oauth2:
        apiKey: 677526813069-6tmd1flqovp5miud67phqlks49bqdo8i.apps.googleusercontent.com
        redirectUri: http://frontend-staging-amzn-us-east-1.repositive.io
      linked-in-oauth2:
        apiKey: 75fsbvpfgi1667
        redirectUri: http://frontend-staging-amzn-us-east-1.repositive.io

